create table translation_requests (
    id int primary key generated by default as identity,
    ip_address varchar(255) not null,
    source_language_code varchar(10) not null,
    input_text text not null,
    target_language_code varchar(10) not null,
    translated_text text not null
);

create table supported_languages (
    id int primary key generated by default as identity,
    code varchar(10) not null,
    "name" varchar(100) not null
)